services:
  postgresql:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=taskmanager
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres

volumes:
  postgresql_data: